name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: crates login
      run: cargo login ${{ secrets.CRATES }}
    - name: publish
      run: cargo publish --manifest-path \home\runner\work\meshuganah\meshuganah\Cargo.toml
